Project2_QuanLyVanBan/QuanLyVanBan/Areas/Admin/Controllers/DocumentCategoryController.cs
using Models.Dao;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyVanBan.Areas.Admin.Controllers
{
    public class DocumentCategoryController : BaseController
    {
        // GET: Admin/DocumentCategory
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            var model = new DocumentCategoryDao().ListAllPaging(page, pageSize);
            return View(model);
        }

        [ChildActionOnly]
        public ActionResult Category()
        {
            var model = new DocumentCategoryDao().ListAll();
            return View(model);
        }

        [HttpDelete]
        public ActionResult Delete(long id)
        {
            new DocumentCategoryDao().Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult EditDocument(long id)
        {
            var model = new DocumentCategoryDao().ViewDetail(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(DocumentCategory docCate)
        {
            if (ModelState.IsValid)
            {
                var dao = new DocumentCategoryDao();
                docCate.CreatedDate = DateTime.Now;
                docCate.ShowOnHome = false;
                docCate.Status = true;

                long id = dao.Insert(docCate);
                if (id > 0)
                {
                    SetAlert("Add User Successful!!", "success");
                    return RedirectToAction("Index", "User");
                }
                else
                {
                    ModelState.AddModelError("", "Add user not successfull!!");
                }
            }

            return View("Index");
        }

        [HttpPost]
        public ActionResult EditDocument(DocumentCategory docCate)
        {
            if (ModelState.IsValid)
            {
                var dao = new DocumentCategoryDao();

                var result = dao.Update(docCate);
                if (result)
                {
                    SetAlert("Edit User Successful!!", "success");
                    return RedirectToAction("Index", "User");
                }
                else
                {
                    ModelState.AddModelError("", "Update user not successfull!!");
                }
            }

            return View("Index");
        }
    }
}

Project2_QuanLyVanBan/QuanLyVanBan/Controllers/DocumentController.cs
using Models.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyVanBan.Controllers
{
    public class DocumentController : Controller
    {
        // GET: Document
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Category(long id, int page = 1, int pageSize = 8)
        {
            var category = new DocumentCategoryDao().ViewDetail(id);
            ViewBag.Category = category;
            int total = 0;
            var model = new DocumentDao().ListAllToPage(id, ref total, page, pageSize);

            ViewBag.Total = total;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)total / (double)pageSize);

            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        public ActionResult ListDocSearch(string searchString, int page = 1, int pageSize = 1)
        {
            int total = 0;
            var model = new DocumentDao().ListDocSearch(searchString, ref total, page, pageSize);

            ViewBag.SearchString = searchString;
            ViewBag.Total = total;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)(total / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }

        public ActionResult Detail(long id)
        {
            var model = new DocumentDao();
            var category = new DocumentCategoryDao();
            var document = model.ViewDetail(id);
            ViewBag.ListDocument = model.ListDocument(document.CategotyID, 4);
            ViewBag.ListCategory = category.ListAll();
            ViewBag.Category = category.ViewDetail(document.CategotyID.Value);
            return View(document);
        }
    }
}

Project2_QuanLyVanBan/QuanLyVanBan/Views/Shared/DocumentCategory.cshtml
@model List<Models.EF.DocumentCategory>
<div class="header_bottom_left">
    <div class="categories">
        <ul>
            <h3>Categories</h3>
            @foreach (var item in Model)
            {
                <li><a href="/tai-lieu/@item.MetaTitle-@item.ID">@item.Name</a></li>
            }
        </ul>
    </div>
</div>

Project2_QuanLyVanBan/QuanLyVanBan/Views/Shared/_FilterDocument.cshtml
@using (Html.BeginForm("ListDocSearch", "Document", FormMethod.Post))
{
    <div class="search-text">
        <div class="row form-group">
            <div class="input-search">
                <input type="text" value="" class="form-control" name="searchString" />
            </div>
            <div class="btn-search">
                <button type="submit" class="btn btn-success">Tìm kiếm</button>
            </div>
        </div>
    </div>
}

Project2_QuanLyVanBan/QuanLyVanBan/Views/Shared/_Layout.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<head>
    <title>Free Home Shoppe Website Template | Home :: w3layouts</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/Assets/client/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Assets/client/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Assets/client/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Assets/client/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Assets/client/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Assets/client/css/easy-responsive-tabs.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="~/Assets/client/css/global.css">

    <script src="~/Assets/client/js/jquery-1.11.3.min.js"></script>
    <script src="~/Assets/client/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Assets/client/js/move-top.js"></script>
    <script type="text/javascript" src="~/Assets/client/js/easing.js"></script>
    <script type="text/javascript" src="~/Assets/client/js/startstop-slider.js"></script>
    <script src="~/Assets/client/js/easyResponsiveTabs.js" type="text/javascript"></script>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p><span>Need help?</span> call us <span class="number">+84-964-042051</span></span></p>
                </div>
                <div class="account_desc">
                    <ul>
                        <li><a href="/Feedback/Create">Thắc mắc</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    <a href="/Home/Index"><img src="~/Assets/client/images/logoWeb.png" alt="" /></a>
                </div>
                @RenderSection("FilterHead", required: false)
                <div class="clear"></div>
            </div>
            @RenderSection("DocumentCategory", required:false)
        </div>
        @RenderBody()
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">

                </div>
                <div class="col_1_of_4 span_1_of_4">

                </div>
                <div class="col_1_of_4 span_1_of_4">

                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Contact</h4>
                    <ul>
                        <li><span>+84-964-042051</span></li>
                    </ul>
                    <div class="social-icons">
                        <h4>Follow Us</h4>
                        <ul>
                            <li><a href="#" target="_blank"><img src="~/Assets/client/images/facebook.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="~/Assets/client/images/twitter.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"><img src="~/Assets/client/images/skype.png" alt="" /> </a></li>
                            <li><a href="#" target="_blank"> <img src="~/Assets/client/images/dribbble.png" alt="" /></a></li>
                            <li><a href="#" target="_blank"> <img src="~/Assets/client/images/linkedin.png" alt="" /></a></li>
                            <div class="clear"></div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy_right">
            <p>&copy; Manage Document. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
        </div>
    </div>
    <script type="text/javascript">
                    $(document).ready(function () {
                        $().UItoTop({ easingType: 'easeOutQuart' });

                    });
    </script>
    <a href="#" id="toTop"><span id="toTopHover"> </span></a>
</body>
</html>